using System;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public class Enemy : MonoBehaviour
{


    public static Enemy Create(Vector3 position)
    {
        Transform enemyTransform = Instantiate(GameAssets.Instance.pfenemy, position, Quaternion.identity);

        Enemy enemy = enemyTransform.GetComponent<Enemy>();

        return enemy;
    }

    private float lookForTargetTimer;
    private float lookForTargetTimerMax = .2f;
    private HealthSystem healthSystem;
    private Transform targetTransform;
    private Rigidbody2D rigidBody2D;

    private void Start()
    {
        rigidBody2D = GetComponent<Rigidbody2D>();

        if (CriadorDeConstrucao.Instance.GetHQBuilding() != null)
        {
            targetTransform = CriadorDeConstrucao.Instance.GetHQBuilding().transform;
        }

        healthSystem = GetComponent<HealthSystem>();

        healthSystem.OnDamaged += HealthSystem_OnDamaged;
        healthSystem.OnDied += healthSystem_OnDied;

        lookForTargetTimer = UnityEngine.Random.Range(0f, lookForTargetTimerMax);
    }

    private void HealthSystem_OnDamaged(object sender, EventArgs e)
    {

    }

    private void healthSystem_OnDied(object sender, EventArgs e)
    {
        Destroy(gameObject);

    }

    private void Update()
    {
        HandleMovement();
        HandleTargeting();
    }

    private void OnCollisionEnter2D(Collision2D collision)
    {
        Building building = collision.gameObject.GetComponent<Building>();
        if (building != null)
        {
            //collided
            HealthSystem healthSystem = building.GetComponent<HealthSystem>();
            healthSystem.Damage(10);
            this.healthSystem.Damage(99);
        }
    }

    private void HandleMovement()
    {
        if (targetTransform.position != null)
        {
            Vector3 moveDir = (targetTransform.position - transform.position).normalized;

            float moveSpeed = 6f;

            rigidBody2D.velocity = moveDir * moveSpeed;
        }
        else
        {
            rigidBody2D.velocity = Vector2.zero;
        }
    }

    private void HandleTargeting()
    {
        if (lookForTargetTimer < 0f)
        {
            lookForTargetTimer += lookForTargetTimerMax;
            LookForTarget();
        }
    }

    private void LookForTarget()
    {
        float targetMaxRadius = 10f;
        Collider2D[] collider2DArray = Physics2D.OverlapCircleAll(transform.position, targetMaxRadius);

        foreach (Collider2D collider2D in collider2DArray)
        {
            Building building = collider2D.GetComponent<Building>();

            if (building != null)
            {
                if (targetTransform == null)
                {
                    targetTransform = building.transform;
                }
                else
                {
                    if (Vector3.Distance(transform.position, building.transform.position) < Vector3.Distance(transform.position, targetTransform.position))
                    {
                        targetTransform = building.transform;
                    }
                }

            }
        }
        if (targetTransform == null)
        {
            if (CriadorDeConstrucao.Instance.GetHQBuilding() != null)
            {
                targetTransform = CriadorDeConstrucao.Instance.GetHQBuilding().transform;
            }
        }

    }

}
